export const SI_ANALISE_AGUARDANDO_ANALISE = 0;
export const SI_ANALISE_EM_ANALISE = 1;
export const SI_ANALISE_ANALISADO = 2;
export const SI_ANALISE_FINALIZADA = 3;
export const SI_ANALISE_EM_VALIDACAO = 4;
export const SI_ANALISE_VALIDADO = 5;
export const SI_ANALISE_FINALIZADA_COORDENADOR = 6;
export const SI_ANALISE_COMPLEMENTAR_DEVOLVIDO = 7;

export const TIPO_ANALISE_CONTEUDO = 0;
export const TIPO_ANALISE_CUSTO_PRODUTO = 1;
export const TIPO_ANALISE_CUSTO_ADMINISTRATIVO = 2;
export const TIPO_ANALISE_PRODUTO_COMPLETO = 3;
