<script>
	jqAjaxLink('<?php echo $this->url(array('controller' => 'avaliarprojetoscomissao', 'action' => 'listarprojetos')); ?>','','gridProjetos');
</script>
<!-- ========== IN&iacute;CIO BREADCRUMB (LINKS TOPO) ========== -->
<div id="breadcrumb">
	<ul>
		<li><a href="<?php echo $this->url(array('controller' => 'principal', 'action' => ''), '', true); ?>" title="Ir para p&aacute;gina Inicial">IN&iacute;CIO</a></li>
		<li><a href="<?php echo $this->url(array('controller' => 'avaliarprojetoscomissao', 'action' => 'avaliarcomissao'), '', true); ?>" title="Ir para Avaliar Projeto Comissao">Avaliar Projeto Comissao</a></li>
		<li class="last">Avaliar Projeto Comissao</li>
	</ul>
</div>
<!-- ========== FIM BREADCRUMB (LINKS TOPO) ========== -->
<div id="titulo">
    <div>Avaliar projeto comiss&atilde;o<span class="voltar"><a href="#" onclick="voltar();">Voltar</a></span></div>
</div>

<div id="conteudo">
<div id='gridProjetos'></div>
<!-- ========== FIM PAGINAÇÂO ========== -->

</div>
<!-- ========== FIM CONTE&uacute;DO ========== -->
<!-- ========== IN&iacute;CIO RODAP&eacute; DO CONTE&uacute;DO ========== -->
<div id="rodapeConteudo"><span></span></div>
<!-- ========== FIM RODAP&eacute; DO CONTE&uacute;DO ========== -->
<br clear="all" />
