export const PERFIL_TECNICO_ACOMPANHAMENTO = 121;
export const PERFIL_COORDENADOR_ACOMPANHAMENTO = 122;
export const PERFIL_COORDENADOR_GERAL_ACOMPANHAMENTO = 123;
export const PERFIL_SUPERINTENDENTE_DE_VINCULADA = 153;
export const PERFIL_PRESIDENTE_DE_VINCULADA = 154;
export const PERFIL_PARECERISTA = 94;
export const PERFIL_COORDENADOR_DE_PARECER = 93;

export const PERFIL_PROPONENTE = 1111;
export const PERFIL_DIRETOR = 148;
export const PERFIL_SECRETARIO = 149;
