export default {
    data: () => ({
        TP_DILIGENCIA_ANALISE_TECNICA: 124,
        SITUACAO_DILIGENCIA_ANALISE_TECNICA: 'B14',
        SI_ANALISE_AGUARDANDO_ANALISE: 0,
        SI_ANALISE_EM_ANALISE: 1,
        SI_ANALISE_ANALISADO: 2,
        SI_ANALISE_FINALIZADO: 3,
    }),
};
