export default {
    data() {
        return {
            mxVinculadas: [
                {
                    Codigo: 91,
                    Sigla: 'IPHAN',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 1,
                },
                {
                    Codigo: 92,
                    Sigla: 'FUNARTE',
                    idSecretaria: 92,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 1,
                },
                {
                    Codigo: 93,
                    Sigla: 'FBN',
                    idSecretaria: 93,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 1,
                },
                {
                    Codigo: 94,
                    Sigla: 'FCP',
                    idSecretaria: 94,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 1,
                },
                {
                    Codigo: 95,
                    Sigla: 'FCRB',
                    idSecretaria: 95,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 1,
                },
                {
                    Codigo: 160,
                    Sigla: 'SAV',
                    idSecretaria: 160,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 1,
                },
                {
                    Codigo: 335,
                    Sigla: 'IBRAM',
                    idSecretaria: 335,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 1,
                },
                {
                    Codigo: 262,
                    Sigla: 'SEFIC',
                    idSecretaria: 251,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
            ],
            mxVinculadasIphan: [
                {
                    Codigo: 113,
                    Sigla: 'IPHAN / AM',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 114,
                    Sigla: 'IPHAN / PA',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 115,
                    Sigla: 'IPHAN / MA',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 116,
                    Sigla: 'IPHAN / CE',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 117,
                    Sigla: 'IPHAN / PE',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 118,
                    Sigla: 'IPHAN / RJ',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 119,
                    Sigla: 'IPHAN / BA',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 120,
                    Sigla: 'IPHAN / SE',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 121,
                    Sigla: 'IPHAN / SP',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 122,
                    Sigla: 'IPHAN / PR',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 123,
                    Sigla: 'IPHAN / SC',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 124,
                    Sigla: 'IPHAN / RS',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 125,
                    Sigla: 'IPHAN / MG',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 126,
                    Sigla: 'IPHAN / GO',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 343,
                    Sigla: 'IPHAN/DPI',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 344,
                    Sigla: 'IPHAN / DF',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 345,
                    Sigla: 'IPHAN/DEPAM',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 346,
                    Sigla: 'IPHAN/COGEDIP',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 347,
                    Sigla: 'IPHAN/COPEDOC',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 348,
                    Sigla: 'IPHAN / RR',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 349,
                    Sigla: 'IPHAN / AP',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 350,
                    Sigla: 'IPHAN / TO',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 351,
                    Sigla: 'IPHAN / MT',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 352,
                    Sigla: 'IPHAN / RO',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 353,
                    Sigla: 'IPHAN / AC',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 354,
                    Sigla: 'IPHAN / AL',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 355,
                    Sigla: 'IPHAN / MS',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 356,
                    Sigla: 'IPHAN / PI',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 357,
                    Sigla: 'IPHAN / PB',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 358,
                    Sigla: 'IPHAN / RN',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
                {
                    Codigo: 359,
                    Sigla: 'IPHAN / ES',
                    idSecretaria: 91,
                    Vinculo: 1,
                    Status: 0,
                    stVinculada: 0,
                },
            ],
        };
    },
};
