<?php $gitTag = '?v=' . $this->gitTag(); ?>

<link href="/public/dist/css/manifest.css<?= $gitTag; ?>" rel="stylesheet">
<link href="/public/dist/css/vendor.css<?= $gitTag; ?>" rel="stylesheet">

<div class="container-fluid">
    <div class="row">
        <?= $this->pageTitle('Visualiza&ccedil;&atilde;o da proposta', []); ?>
        <div id="container-vue">
            <proposta-proponente :id-pre-projeto="<?= $this->idPreProjeto; ?>"></proposta-proponente>
        </div>
    </div>
</div>
