<html>
    <head>
        <title>Salic</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
        <link href="/public/css/vuetify.min.css" rel="stylesheet">
        <link href="/public/css/fonts.css" rel="stylesheet">
        <link href="/public/dist/img/favicons/android-icon-192x192.png" rel="icon" type="image/png" sizes="192x192">
        <link href="/public/dist/img/favicons/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180">
        <link href="/public/dist/img/favicons/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152">
        <link href="/public/dist/img/favicons/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144">
        <link href="/public/dist/img/favicons/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120">
        <link href="/public/dist/img/favicons/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
        <link href="/public/dist/img/favicons/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76">
        <link href="/public/dist/img/favicons/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
        <link href="/public/dist/img/favicons/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60">
        <link href="/public/dist/img/favicons/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57">
        <link href="/public/dist/img/favicons/favicon-16x16.png" rel="icon" type="image/png" sizes="16x16">
        <link href="/public/dist/img/favicons/favicon-96x96.png" rel="icon" type="image/png" sizes="96x96">
        <link href="/public/dist/img/favicons/favicon-32x32.png" rel="icon" type="image/png" sizes="32x32">
        <link href="/public/dist/img/favicons/favicon.ico" rel="favicon">
        <style>
            body {
                font-family: 'Roboto', sans-serif;
            }
        </style>
    </head>
    <body>
        <div id="app"></div>
        <?php $gitTag = '?v=' . $this->gitTag(); ?>
        <script type="text/javascript" charset="utf-8" src="/public/dist/js/manifest.js<?= $gitTag; ?>"></script>
        <script type="text/javascript" charset="utf-8" src="/public/dist/js/vendor.js<?= $gitTag; ?>"></script>
        <script type="text/javascript" charset="utf-8" src="/public/dist/js/avaliacao_resultados.js<?= $gitTag; ?>"></script>
    </body>
</html>
