<style>
    p { margin: 40px; }
    div {
        text-align:justify;
        text-justify:inter-word;
    }
</style>
<p align="center">
    <img width="100" src="<?php echo $this->baseUrl() . '/public/img/brasao.jpg'; ?>"/>
</p>
<p align="center">
    MINIST&eacute;RIO DA TURISMO<br>
    Secretaria de Fomento e Incentivo &aacute; Cultura<br>
    Esplanada dos Minist&eacute;rios, Bloco "B"<br>
    Bras&iacute;lia/DF - CEP 70.068-900
</p>
<div>
    <p lang="pt-BR" align="LEFT">
        <strong>Manifestação Final do T&eacute;cnico de Prestação de Contas: {manifestacaoParecerTecnico}</strong>
    </p>
    <p lang="pt-BR" align="LEFT">
        <strong>Parecer T&eacute;cnico :</strong></br>
        {parecerDoTecnico}
    </p>
</div>
