<div class="content padding20 clearfix">

    <div class="row">
        <div class="col s1"></div>
        <div class="col s10 center-align">
            <div>
                <img src="/public/img/planalto_presidencia_simbolosnacionais_brasao.gif" style="height:120px">
            </div>
            <div class="center-align" style="font-size: 23px;">
                MINIST&Eacute;RIO DA CIDADANIA
            </div>
            <?php if ((int)$this->orgaoSuperior == (int)\Orgaos::ORGAO_SUPERIOR_SEFIC): ?>
                <div class="center-align" style="font-size: 23px;">
                    SECRETARIA ESPECIAL DA CULTURA
                </div>
                <div class="center-align" style="font-size: 23px; color: black;">
                    Secretaria de Fomento e Incentivo &agrave; Cultura - SEFIC
                </div>
            <?php else: ?>
                <div class="center-align" style="font-size: 23px;">
                    <?php echo $this->nomeOrgao; ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="col s1"></div>
    </div>
    <div class="row">
        <div class="col s1"></div>
        <div class="col s10 center-align">
            <h3 style="font-size: 23px; color: black;"><?php echo $this->titulo ?></h3>
        </div>
        <div class="col s1"></div>
    </div>
    <div class="row">
        <div class="col s1"></div>
        <div class="col s2">
            <b style="color: black">PRONAC</b>
            <p class="bold padding10 bordered">
                <?php
                echo $this->projeto['AnoProjeto'] . $this->projeto['Sequencial'];
                ?>
            </p>
        </div>
        <div class="col s8">
            <label style="color: black">Nome do Projeto</label>
            <p class="bold padding10 bordered">
                <?php
                echo $this->projeto['NomeProjeto'];
                ?>
            </p>
        </div>
        <div class="col s1"></div>
    </div>

    <div class="row">
        <div class="col s1"></div>
        <div class="col s2">
            <label style="color: black">CNPJ / CPF</label>
            <p class="bold padding10 bordered">
                <?= Mascara::addMaskCpfCnpj($this->projeto['CgcCpf']); ?>
        </div>
        <div class="col s8">
            <label style="color: black">Proponente</label>
            <br/>
            <p class="bold padding10 bordered">
                <?php
                echo $this->nomeAgente;
                ?>
            </p>
        </div>
        <div class="col s1"></div>
    </div>
    <div class="row">
        <div class="col s1"></div>
        <div class="col s1">
            <label style="color: black">UF</label>
            <p class="bold padding10 bordered">
                <?php
                echo $this->projeto['UfProjeto'];
                ?>
            </p>
        </div>
        <div class="col s3">
            <label style="color: black">&Aacute;rea Cultural</label>
            <p class="bold padding10 bordered">
                <?php
                echo $this->areaCultural['Descricao'];
                ?>
            </p>
        </div>
        <div class="col s4">
            <label style="color: black">Segmento Cultural</label>
            <p class="bold padding10 bordered">
                <?php
                echo $this->segmentoCultural['Descricao'];
                ?>
            </p>
        </div>
        <div class="col s2">
            <label style="color: black">Per&iacute;odo de Execu&ccedil;&atilde;o</label>
            <p class="padding10 bordered">
                <b>
                    <?php
                    echo Data::tratarDataZend($this->projeto['DtInicioExecucao'], 'Brasileira');
                    ?>
                </b>
                a
                <b>
                    <?php
                    echo Data::tratarDataZend($this->projeto['DtFimExecucao'], 'Brasileira');
                    ?>
                </b>
            </p>
        </div>
        <div class="col s1"></div>
    </div>
    <div class="row">
        <div class="col s1"></div>
        <div class="col s10">
            <label style="color: black">Resumo do Projeto</label>
            <p class="bold bordered padding10">
                <?php
                echo $this->dadosEnquadramento[0]->ResumoProjeto;
                ?>
        </div>
    </div>
    <br/><br/>
    <div class="row">
        <div class="col s1"></div>
        <div class="col s10">
            <label style="color: black">Mem&oacute;ria de C&aacute;lculo</label>
            <div class="bordered padding10">
                <div class="row">
                    <table class="table margin0" style="width: 100%">
                        <tr>
                            <td align="center" class="bold" colspan="2">Proponente</td>
                            <td>&nbsp;</td>
                            <td align="center" class="bold" colspan="2">Parecerista</td>
                        </tr>

                        <tr>
                            <td align="center">Vl. Solicitado</td>
                            <td class="right-align">
                                R$<?php echo number_format($this->dadosEnquadramento[0]->VlSolicitado, 2, ',', '.'); ?></td>
                            <td>&nbsp;</td>
                            <td align="center">Vl. Sugerido</td>
                            <td class="right-align">
                                R$<?php echo number_format($this->dadosParecer[0]['SugeridoReal'], 2, ',', '.'); ?></td>
                        </tr>

                        <tr>
                            <td align="center">Vl. Outras Fontes</td>
                            <td class="right-align">
                                R$<?php echo number_format($this->dadosEnquadramento[0]->VlOutrasFontes, 2, ',', '.'); ?></td>
                            <td>&nbsp;</td>
                            <td align="center">Vl. Outras Fontes</td>
                            <td class="right-align">
                                R$<?php echo number_format($this->dadosEnquadramento[0]->VlOutrasFontesAprovado, 2, ',', '.'); ?></td>
                        </tr>

                        <tr>
                            <td align="center" class="bold">Vl. Projeto</td>
                            <td class="right-align">
                                R$<?php echo number_format($this->dadosEnquadramento[0]->VlProjeto, 2, ',', '.'); ?></td>
                            <td>&nbsp;</td>
                            <td align="center" class="bold">Vl. Sugerido Total</td>
                            <td class="right-align">
                                R$<?= number_format($this->dadosParecer[0]['SugeridoReal'] + $this->dadosEnquadramento[0]->VlOutrasFontesAprovado, 2, ',', '.'); ?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <br/><br/>
    <div class="row">
        <div class="col s1"></div>
        <div class="col s10">
            <label style="color: black;">Posicionamento T&eacute;cnico</label>
            <div class="bold padding10 bordered">
                <?php echo $this->dadosParecer[0]['p.tpResultado']; ?>
            </div>
        </div>
    </div>
    <br/><br/>
    <div class="row">
        <div class="col s1"></div>
        <div class="col s10">
            <label style="color: black;">Parecer T&eacute;cnico</label>
            <div class="bold padding10 bordered" style="text-align: justify;">
                <?php echo $this->dadosParecer[0]['ResumoParecer']; ?>
            </div>
        </div>
    </div>
</div>
